FROM php:7.0.32-fpm
LABEL version="1.0"
LABEL description="php:7.0.32-fpm"
LABEL maintainer="stefan<losthorse007@gmail.com>"
#安装环境
RUN set -ex \
&& apt-get update \
 --- 安装扩展 — #
#mysql pdo
&& docker-php-ext-install pdo_mysql \
&& docker-php-ext-enable  pdo_mysql.so \
# redis
&& pecl install redis \
&& docker-php-ext-enable redis.so